apiVersion: apps/v1
kind: Deployment
metadata:
  name: structurizr
  labels:
    app: structurizr
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: structurizr
  template:
    metadata:
      labels:
        app: structurizr
    spec:
      containers:
        - name: structurizr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
